services:
  overleaf:
    restart: always
    image: sharelatex/sharelatex:5.5.4
    container_name: overleaf
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    # Port mapping - comment out when deploying to Coolify/Traefik
    # For local development, uncomment the line below:
    # ports:
    #   - "80:80"
    expose:
      - "80"  # Expose port to other containers (Traefik can access)
    volumes:
      - ./data/sharelatex:/var/lib/overleaf
    environment:
      # Base Configuration
      OVERLEAF_APP_NAME: ${OVERLEAF_APP_NAME:-Overleaf Community Edition}
      OVERLEAF_SITE_URL: ${OVERLEAF_SITE_URL:-http://localhost}
      OVERLEAF_NAV_TITLE: ${OVERLEAF_NAV_TITLE:-Overleaf}
      OVERLEAF_ADMIN_EMAIL: ${OVERLEAF_ADMIN_EMAIL:-admin@example.com}
      OVERLEAF_BEHIND_PROXY: ${OVERLEAF_BEHIND_PROXY:-false}
      
      # Database & Cache
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      OVERLEAF_REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Email Configuration (SMTP)
      OVERLEAF_EMAIL_FROM_ADDRESS: ${OVERLEAF_EMAIL_FROM_ADDRESS:-}
      OVERLEAF_EMAIL_SMTP_HOST: ${OVERLEAF_EMAIL_SMTP_HOST:-}
      OVERLEAF_EMAIL_SMTP_PORT: ${OVERLEAF_EMAIL_SMTP_PORT:-587}
      OVERLEAF_EMAIL_SMTP_SECURE: ${OVERLEAF_EMAIL_SMTP_SECURE:-false}
      OVERLEAF_EMAIL_SMTP_USER: ${OVERLEAF_EMAIL_SMTP_USER:-}
      OVERLEAF_EMAIL_SMTP_PASS: ${OVERLEAF_EMAIL_SMTP_PASS:-}
      OVERLEAF_EMAIL_SMTP_LOGGER: ${OVERLEAF_EMAIL_SMTP_LOGGER:-false}
      OVERLEAF_EMAIL_SMTP_NAME: ${OVERLEAF_EMAIL_SMTP_NAME:-}
      EMAIL_CONFIRMATION_DISABLED: ${EMAIL_CONFIRMATION_DISABLED:-true}
      
      # Features
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
    stop_grace_period: 60s

  mongo:
    restart: always
    image: mongo:6.0
    container_name: overleaf-mongo
    command: --replSet overleaf
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:6.2
    container_name: overleaf-redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
